# config/config.yaml

# SENM simulation parameters
senm:
  nx: 500
  ny: 500
  kernel: "3"
  nu: "9.000000e-05"
  num_realizations: 100
  chosen_kernels: ["2", "3", "5"]

# File templates for SENM output
senm_templates:
  spatial: "AConf_NX{nx}_NY{ny}_NU{nu}_Square_Kernsize{kernel}_rel.{realization}"
  abundance: "Abund_NX{nx}_NY{ny}_NU{nu}_Square_Kernsize{kernel}_rel.{realization}"
  path: "senm/"

# Real forest datasets
forests:
  name: ["barro"]
  templates: 
    raw_data_template: "bcitree{census}.dat"
    path_template: "data/{forest}/"
    census_template: "{forest}_{census}.csv"
    abundance_template: "{forest}_abundances_{census}.csv"
    names_template: "names_{forest}_{census}.txt"
  censuses: [1, 2, 3, 4, 5, 6, 7, 8]

# Grid settings
grid:
  forest:
    width: 1000
    height: 500
  senm:
    width: 500
    height: 500

# Defaults for analysis
analysis:
  num_species: [100,150,200]
  resolutions: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

